services:
  app: 
    build: .
    env_file:
      - .env.development
    ports:
      - 8090:8090
    volumes:
      - ./config.toml:/payment-app/config.toml
      - ./account_keys:/payment-app/account_keys
      - ./scripts:/payment-app/scripts