services:
  ludium-local-db:
    container_name: ludium-local-db
    image: postgres:13
    env_file:
      - .env.development
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: {}